services:
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - actual_network
      - blog_network
    restart: unless-stopped

networks:
  actual_network:
    external: true
    name: actual_docker_install_default
  blog_network:
    external: true
    name: blog_default

volumes:
  caddy_data:
  caddy_config:
