services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - actual_network
      - blog_network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM;
                  while :; do
                    certbot renew;
                    sleep 12h & wait $${!};
                  done;"
    restart: unless-stopped

networks:
  actual_network:
    external: true
    name: actual_default
  blog_network:
    external: true
    name: personal_blog_default
